apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
  
stringData:
  
  password: YUIidhb667

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
  
stringData:
  username: kodekloud_pop
  password: YchZHRcLkL

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
  
stringData:
  
  database: kodekloud_db9


